from __future__ import annotations
import os
import json
from dataclasses import dataclass
from typing import Optional, Dict, List
from pathlib import Path
from enum import Enum


class Platform(Enum):
    """Git platform for PR operations."""
    GITHUB = "github"
    GITLAB = "gitlab"


@dataclass
class PRConfig:
    """Configuration for creating a pull/merge request."""
    platform: Platform
    token: str
    repo_owner: str
    repo_name: str
    base_branch: str = "main"
    head_branch: str = "rebuild-auto"
    title: str = "Rebuild: Automated Refactor"
    body: str = ""


@dataclass
class PRResult:
    """Result of PR creation."""
    success: bool
    pr_url: Optional[str] = None
    pr_number: Optional[int] = None
    error: Optional[str] = None


class PRService:
    """Service for creating pull/merge requests on GitHub/GitLab."""

    def __init__(self, config: PRConfig):
        self.config = config

    def create_pr(self, diff_summary: str, refactor_suggestions: List[str]) -> PRResult:
        """Create a PR with AI-generated summary and refactor suggestions."""
        body = self._generate_pr_body(diff_summary, refactor_suggestions)

        if self.config.platform == Platform.GITHUB:
            return self._create_github_pr(body)
        elif self.config.platform == Platform.GITLAB:
            return self._create_gitlab_mr(body)
        else:
            return PRResult(success=False, error=f"Unsupported platform: {self.config.platform}")

    def _generate_pr_body(self, diff_summary: str, refactor_suggestions: List[str]) -> str:
        """Generate PR body with AI summary and refactor suggestions."""
        body = f"""# {self.config.title}

## Summary
This PR contains automated refactor suggestions generated by Rebuild.

## Analysis
{diff_summary}

## Refactor Suggestions
"""
        for i, suggestion in enumerate(refactor_suggestions, 1):
            body += f"{i}. {suggestion}\n"

        body += """
## How to Review
- Review the diff for each suggested change
- Test the changes locally
- Approve or request changes as needed

---
Generated by [Rebuild](https://github.com/semcod/rebuild) - Automated Code Analysis & Refactoring
"""
        return body

    def _create_github_pr(self, body: str) -> PRResult:
        """Create a pull request on GitHub."""
        try:
            import requests

            url = f"https://api.github.com/repos/{self.config.repo_owner}/{self.config.repo_name}/pulls"
            headers = {
                "Authorization": f"token {self.config.token}",
                "Accept": "application/vnd.github.v3+json",
            }

            data = {
                "title": self.config.title,
                "body": body,
                "head": self.config.head_branch,
                "base": self.config.base_branch,
            }

            response = requests.post(url, json=data, headers=headers, timeout=30)

            if response.status_code == 201:
                result = response.json()
                return PRResult(
                    success=True,
                    pr_url=result["html_url"],
                    pr_number=result["number"],
                )
            else:
                return PRResult(
                    success=False,
                    error=f"GitHub API error: {response.status_code} - {response.text[:200]}",
                )
        except ImportError:
            return PRResult(success=False, error="requests library not installed")
        except Exception as e:
            return PRResult(success=False, error=f"Failed to create GitHub PR: {str(e)}")

    def _create_gitlab_mr(self, body: str) -> PRResult:
        """Create a merge request on GitLab."""
        try:
            import requests

            url = f"https://gitlab.com/api/v4/projects/{self.config.repo_owner}%2F{self.config.repo_name}/merge_requests"
            headers = {
                "PRIVATE-TOKEN": self.config.token,
            }

            data = {
                "title": self.config.title,
                "description": body,
                "source_branch": self.config.head_branch,
                "target_branch": self.config.base_branch,
            }

            response = requests.post(url, json=data, headers=headers, timeout=30)

            if response.status_code == 201:
                result = response.json()
                return PRResult(
                    success=True,
                    pr_url=result["web_url"],
                    pr_number=result["iid"],
                )
            else:
                return PRResult(
                    success=False,
                    error=f"GitLab API error: {response.status_code} - {response.text[:200]}",
                )
        except ImportError:
            return PRResult(success=False, error="requests library not installed")
        except Exception as e:
            return PRResult(success=False, error=f"Failed to create GitLab MR: {str(e)}")


def load_config_from_env() -> Optional[PRConfig]:
    """Load PR configuration from environment variables."""
    platform_str = os.getenv("REBUILD_PR_PLATFORM", "").lower()
    if not platform_str:
        return None

    try:
        platform = Platform(platform_str)
    except ValueError:
        return None

    token = os.getenv("REBUILD_PR_TOKEN")
    repo_owner = os.getenv("REBUILD_PR_REPO_OWNER")
    repo_name = os.getenv("REBUILD_PR_REPO_NAME")

    if not all([token, repo_owner, repo_name]):
        return None

    return PRConfig(
        platform=platform,
        token=token,
        repo_owner=repo_owner,
        repo_name=repo_name,
        base_branch=os.getenv("REBUILD_PR_BASE_BRANCH", "main"),
        head_branch=os.getenv("REBUILD_PR_HEAD_BRANCH", "rebuild-auto"),
        title=os.getenv("REBUILD_PR_TITLE", "Rebuild: Automated Refactor"),
    )
