flowchart TD
    SUMD["SUMD<br/>91 funcs"]
    docs__README["docs.README<br/>1 funcs"]
    project__map["project.map<br/>90 funcs"]
    testql_scenarios__generated_from_pytests["testql-scenarios.generated-from-pytests<br/>1 funcs"]
